from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from contextlib import asynccontextmanager
import asyncio
import shutil
import uuid
import os
import json
import base64
import uvicorn
import config  # <--- Global Config
import subprocess
import time
import requests
from transformers import ViTForImageClassification

# <--- NEW IMPORTS AS REQUESTED --->
from xray_filter import is_chest_xray 

# Import agents and dependencies
from synthesis import (
    LocalSynthesisAgent,
    RetrievalAgent,
    LocalLLMReportAgent,
    VisualDescriptionAgent,
    reports_dict,
    vision_encoder,
)

# --- GLOBAL AGENT STORE ---
# We keep agents here so they stay in memory (RAM) and don't reload per request
agents = {}

# --- LIFESPAN MANAGER ---
def check_and_start_ollama():
    """Checks if Ollama is running, and starts it if not."""
    ollama_url = f"{config.BASE_URL}/api/tags"
    try:
        requests.get(ollama_url, timeout=1)
        print("✅ Ollama is already running.")
    except (requests.exceptions.ConnectionError, requests.exceptions.Timeout):
        print("⚠️ Ollama is NOT running. Starting it now...")
        try:
            # Start Ollama in the background
            subprocess.Popen(["ollama", "serve"], shell=True)
            
            # Wait for it to come alive
            print("⏳ Waiting for Ollama to be ready...", end="", flush=True)
            for _ in range(20):
                try:
                    requests.get(ollama_url, timeout=1)
                    print(" Done!")
                    return
                except:
                    time.sleep(1)
                    print(".", end="", flush=True)
            print("\n❌ Failed to start Ollama automatically. Please start it manually.")
        except FileNotFoundError:
             print("\n❌ 'ollama' command not found. Is it installed?")

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup - Clean memory first
    import gc
    import torch
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.synchronize()
    print("🧹 Memory cleaned before startup...")
    
    check_and_start_ollama()
    
    # Initialize Global Model
    global model
    print("Loading Global Vision Model (ViT)...")
    model = ViTForImageClassification.from_pretrained(
        "google/vit-base-patch16-224"
    )
    device = vision_encoder.device
    print(f"\n🚀 STARTUP: Loading AI Models on {device}...")
    print(f"🧠 LLM Engine: {config.OLLAMA_MODEL}")
    
    # Initialize agents globally (all share BioMedCLIP via vision_encoder)
    agents["retrieval"] = RetrievalAgent(vision_encoder, k=3)
    agents["draft"] = LocalLLMReportAgent()
    agents["vision"] = VisualDescriptionAgent()
    agents["synthesis"] = LocalSynthesisAgent()
    
    print("✅ All AI Agents Ready! Server is listening.")
    yield
    print("🛑 Shutting down...")

# Initialize App with lifespan
app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

UPLOAD_DIR = "uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)


@app.post("/api/synthesize-report")
async def synthesize_report(file: UploadFile = File(...)):
    # 1. Save the Uploaded Image
    file_id = str(uuid.uuid4())
    image_path = os.path.join(UPLOAD_DIR, f"{file_id}.png")

    with open(image_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    # 2. VALIDATE: Fast fail using the new xray_filter
    try:
        is_valid, confidence = is_chest_xray(image_path)
        
        if not is_valid:
            # Delete the invalid file
            os.remove(image_path)
            
            # Return error stream instantly without starting agents
            async def error_stream():
                yield json.dumps({
                    "status": "error", 
                    "message": f"Validation Failed: This does not look like a Chest X-Ray (Confidence: {confidence:.1%}). Please upload a valid medical scan."
                }) + "\n"
            return StreamingResponse(error_stream(), media_type="application/x-ndjson")
            
    except Exception as e:
        print(f"⚠️ Validation error: {e}")

    # 3. Create the ASYNC Generator using Pre-Loaded Agents
    # synthesis.py runs generate_explainable_image internally!
    report_generator = agents["synthesis"].generate_final_report(
        draft_agent=agents["draft"],
        vision_agent=agents["vision"],
        retrieval_agent=agents["retrieval"],
        reports_dict=reports_dict,
        image_paths=[image_path]
    )

    # 4. Async Wrapper to Inject Heatmap Generated by Synthesis Agent
    async def process_stream(generator):
        async for chunk in generator:
            try:
                data = json.loads(chunk)
                
                # Intercept the final chunk to attach the Base64 image data
                if data.get("status") == "complete":
                    exp_path = data.get("explainable_image_path")
                    
                    # If synthesis.py successfully created the image, encode it
                    if exp_path and os.path.exists(exp_path) and exp_path != "Normal - No highlights needed":
                        with open(exp_path, "rb") as f:
                            b64_data = base64.b64encode(f.read()).decode("utf-8")
                        data["heatmap"] = f"data:image/png;base64,{b64_data}"
                    else:
                        data["heatmap"] = None
                        
                    yield json.dumps(data) + "\n"
                else:
                    yield chunk
            except Exception:
                yield chunk

    # Return Streaming Response
    return StreamingResponse(
        process_stream(report_generator), 
        media_type="application/x-ndjson"
    )

# ── Health / Metrics Endpoint ──────────────────────
import psutil

_server_start_time = time.time()

@app.get("/api/health")
async def health():
    import torch as _torch
    mem = psutil.virtual_memory()
    result = {
        "status": "healthy",
        "uptime_seconds": int(time.time() - _server_start_time),
        "cpu_percent": psutil.cpu_percent(interval=0.3),
        "memory_used_mb": round(mem.used / (1024 ** 2)),
        "memory_total_mb": round(mem.total / (1024 ** 2)),
        "gpu_available": _torch.cuda.is_available(),
    }
    if _torch.cuda.is_available():
        result["gpu_name"] = _torch.cuda.get_device_name(0)
        result["gpu_memory_used_mb"] = round(_torch.cuda.memory_allocated(0) / (1024 ** 2))
        result["gpu_memory_total_mb"] = round(_torch.cuda.get_device_properties(0).total_memory / (1024 ** 2))
    return result

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)