[pytest]
filterwarnings =
    ignore::FutureWarning
    ignore::UserWarning
    ignore::DeprecationWarning
    ignore:async def functions are not natively supported
    ignore:Unknown pytest.mark.asyncio
    ignore:Unknown pytest.mark.anyio
